// Build EIGHT mazes matched on difficulty.
//
//   node mazes8/scripts/build-set.mjs [--seeds=6000] [--tries=14] [--branch=26] [--length=53]
//
// The brief: every maze has the SAME number of branch points, a SIMILAR path length,
// and genuinely more than one correct path. The existing four fail it — path length
// runs 41-53 and branch points 19-24 — because the old generator matched with loose
// tolerances (+/-12 steps, +/-5 junctions).
//
// So: sample a large pool of braided candidates, then pick the (branch points, path
// length) profile that the most candidates can hit EXACTLY, and take eight visibly
// different mazes from that profile. Branch points are equal by construction; path
// length is held inside a +/-2 band.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { N, START, GOAL, build, divergence, rowsOf, hedgeRuns } from "./lib.mjs";

const arg = (k, d) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${k}=`));
  return hit ? Number(hit.split("=")[1]) : d;
};
const SEEDS = arg("seeds", 6000);
// Shortest hedge run allowed, in cells. 0 disables the repair.
const REPAIR_MIN = arg("repair", 2);
const TRIES = arg("tries", 14);
const WANT = 8;
const LEN_TOL = 2;          // path length may vary by +/-2 moves, no more
const MAX_POCKET = 6;       // dead ends stay shallow, so no long pointless corridors
const MIN_CHOICE = 12;      // branch points that genuinely offer more than one way on
const MIN_LOOPS = 8;
const MIN_DIVERGENCE = 0.10; // no two mazes may be near-copies of each other

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..", "..");
// --out lets a candidate set be built somewhere harmless. Overwriting the live set
// invalidates every stored route, and the hints derive from those, so a cutover has
// to be deliberate rather than a side effect of regenerating.
const OUT = (process.argv.slice(2).find((a) => a.startsWith("--out=")) || "").split("=")[1];
const outDir = OUT ? path.join(root, OUT) : path.join(root, "public", "mazes8");

console.log(`sampling ${SEEDS} seeds x ${TRIES} braidings ...`);
const pool = [];
for (let seed = 1; seed <= SEEDS; seed += 1) {
  for (let t = 0; t < TRIES; t += 1) {
    const c = build(seed, t, [6, 12], REPAIR_MIN, MAX_POCKET);
    if (!c) continue;
    if (c.maxPocket > MAX_POCKET) continue;
    if (c.choicePoints < MIN_CHOICE) continue;
    if (c.loops < MIN_LOOPS) continue;
    pool.push(c);
  }
}
console.log(`usable candidates: ${pool.length}`);

// Pick the profile with the most candidates. Ties break toward the longer path (more
// decisions per trial) unless --length says otherwise, in which case the profile
// nearest that length wins — trial duration is a study-design call, not a maze one.
const WANT_BRANCH = arg("branch", 0);
const WANT_LENGTH = arg("length", 0);
let target = null;
const branchValues = [...new Set(pool.map((c) => c.branchPoints))];
for (const b of branchValues) {
  if (WANT_BRANCH && b !== WANT_BRANCH) continue;
  const atB = pool.filter((c) => c.branchPoints === b);
  for (const L of [...new Set(atB.map((c) => c.pathLength))]) {
    const hits = atB.filter((c) => Math.abs(c.pathLength - L) <= LEN_TOL);
    if (hits.length < WANT * 4) continue;   // want room to choose distinct ones
    const score = WANT_LENGTH ? -Math.abs(L - WANT_LENGTH) * 1000 + hits.length : L * 1000 + hits.length;
    if (!target || score > target.score) target = { branchPoints: b, length: L, hits, score };
  }
}
if (!target) { console.error("no profile had enough candidates — raise --seeds"); process.exit(1); }
console.log(`\ntarget profile: ${target.branchPoints} branch points, path ${target.length} +/-${LEN_TOL}` +
  `  (${target.hits.length} candidates to choose from)\n`);

// Take eight that differ from each other, preferring the ones closest to the target
// length so the set is as tight as it can be.
const ranked = target.hits.slice().sort((a, b) =>
  Math.abs(a.pathLength - target.length) - Math.abs(b.pathLength - target.length) ||
  b.choicePoints - a.choicePoints);
const chosen = [];
for (const c of ranked) {
  if (chosen.length === WANT) break;
  if (chosen.some((p) => divergence(p.g, c.g) < MIN_DIVERGENCE)) continue;
  chosen.push(c);
}
if (chosen.length < WANT) { console.error(`only found ${chosen.length} distinct mazes — lower MIN_DIVERGENCE or raise --seeds`); process.exit(1); }

fs.mkdirSync(outDir, { recursive: true });
console.log("maze     path len  branch pts  choice pts  loops  dead ends  seed");
chosen.forEach((c, i) => {
  const n = i + 1;
  const id = `maze-${n}`;
  console.log(`${id.padEnd(9)}${String(c.pathLength).padEnd(10)}${String(c.branchPoints).padEnd(12)}` +
    `${String(c.choicePoints).padEnd(12)}${String(c.loops).padEnd(7)}${String(c.deadEndBranches).padEnd(11)}${c.seed}`);
  const V = `MAZE8_${n}`;
  fs.writeFileSync(path.join(outDir, `${id}.js`), `// Auto-generated by mazes8/scripts/build-set.mjs (seed ${c.seed}, braiding ${c.tryIndex}).
// One of EIGHT mazes matched on difficulty: every maze in the set has exactly
// ${c.branchPoints} branch points and a path length of ${target.length} +/-${LEN_TOL} moves.
// ${c.loops} loops, and ${c.choicePoints} of the branch points have more than one branch that
// reaches the exit — so there is genuinely more than one correct path.
// Dead-end pockets are capped at ${MAX_POCKET} cells.
const WALL_ROWS = [
${rowsOf(c.g).map((r) => `  "${r}",`).join("\n")}
];

export const ${V}_MAZE_GRID = WALL_ROWS.map((row) => [...row].map(Number));

export const ${V}_MAZE_CONFIG = {
  id: "maze8-${n}-${N}x${N}",
  name: "${N} by ${N} matched maze ${n} of 8",
  maze: ${V}_MAZE_GRID,
  start: { x: ${START.x}, y: ${START.y} },
  entrance: { x: ${START.x}, y: 0 },
  startFacing: 2,
  goal: { x: ${GOAL.x}, y: ${GOAL.y} },
  hintSteps: 3,
  seed: ${c.seed},
};
`);
});

fs.writeFileSync(path.join(outDir, "manifest.json"), JSON.stringify({
  generated_at: new Date().toISOString(),
  generator: "mazes8/scripts/build-set.mjs",
  brief: "eight mazes of similar difficulty: same branch points, similar path length, more than one correct path",
  criteria: {
    branch_points: target.branchPoints,
    path_length: target.length,
    path_length_tolerance: LEN_TOL,
    min_choice_points: MIN_CHOICE,
    min_loops: MIN_LOOPS,
    max_dead_end_pocket: MAX_POCKET,
  },
  mazes: chosen.map((c, i) => ({
    id: `maze-${i+1}`, file: `public/mazes8/maze-${i+1}.js`, seed: c.seed,
    path_length: c.pathLength, branch_points: c.branchPoints,
    choice_points: c.choicePoints, loops: c.loops, dead_end_branches: c.deadEndBranches,
  })),
}, null, 2) + "\n");

console.log(`\nwrote ${WANT} mazes to public/mazes8/ and mazes8/manifest.json`);
