// Auto-generated by mazes8/scripts/build-set.mjs (seed 417, braiding 9).
// One of EIGHT mazes matched on difficulty: every maze in the set has exactly
// 33 branch points and a path length of 37 +/-2 moves.
// 15 loops, and 32 of the branch points have more than one branch that
// reaches the exit — so there is genuinely more than one correct path.
// Dead-end pockets are capped at 6 cells.
const WALL_ROWS = [
  "111111111011111111111",
  "100000001000000000001",
  "101111101010111111101",
  "100000001000000000001",
  "101011111111101010101",
  "101000000000000000001",
  "101111101111101111111",
  "101000000000000000101",
  "101011111110111110101",
  "101000000010000010101",
  "101010101011111010101",
  "101000101010100010001",
  "101111101010101111101",
  "101000101000101000001",
  "101010101010101010101",
  "101010001010001010001",
  "101010101010101010101",
  "100010101010001010001",
  "111110101011111111101",
  "100000100000000000001",
  "111111111110111111111",
];

export const MAZE8_6_MAZE_GRID = WALL_ROWS.map((row) => [...row].map(Number));

export const MAZE8_6_MAZE_CONFIG = {
  id: "maze8-6-10x10",
  name: "10 by 10 matched maze 6 of 8",
  maze: MAZE8_6_MAZE_GRID,
  start: { x: 9, y: 1 },
  entrance: { x: 9, y: 0 },
  startFacing: 2,
  goal: { x: 11, y: 20 },
  hintSteps: 3,
  seed: 417,
};
