// Auto-generated by mazes8/scripts/build-set.mjs (seed 234, braiding 1).
// One of EIGHT mazes matched on difficulty: every maze in the set has exactly
// 33 branch points and a path length of 37 +/-2 moves.
// 17 loops, and 32 of the branch points have more than one branch that
// reaches the exit — so there is genuinely more than one correct path.
// Dead-end pockets are capped at 6 cells.
const WALL_ROWS = [
  "111111111011111111111",
  "100000100010000000001",
  "101010101010111110101",
  "100010100010000000101",
  "101010101011111110101",
  "100010001000000000101",
  "101011111111111110101",
  "101000001000100000001",
  "101111101010101111101",
  "101000000000100010001",
  "101011111011111010101",
  "100000100010000010101",
  "111110101010101010101",
  "100000100010100010101",
  "101011111010111110101",
  "100000000000100000101",
  "111110101111101111101",
  "100000000000000000001",
  "101111101111111011111",
  "100000000000000000001",
  "111111111110111111111",
];

export const MAZE8_4_MAZE_GRID = WALL_ROWS.map((row) => [...row].map(Number));

export const MAZE8_4_MAZE_CONFIG = {
  id: "maze8-4-10x10",
  name: "10 by 10 matched maze 4 of 8",
  maze: MAZE8_4_MAZE_GRID,
  start: { x: 9, y: 1 },
  entrance: { x: 9, y: 0 },
  startFacing: 2,
  goal: { x: 11, y: 20 },
  hintSteps: 3,
  seed: 234,
};
