// Auto-generated by mazes8/scripts/build-set.mjs (seed 506, braiding 6).
// One of EIGHT mazes matched on difficulty: every maze in the set has exactly
// 33 branch points and a path length of 37 +/-2 moves.
// 16 loops, and 32 of the branch points have more than one branch that
// reaches the exit — so there is genuinely more than one correct path.
// Dead-end pockets are capped at 6 cells.
const WALL_ROWS = [
  "111111111011111111111",
  "100000000000100000001",
  "111110101010101111101",
  "100000100010101000001",
  "101011111010101010101",
  "101000101010101010001",
  "101010101010101011111",
  "101010101010000010001",
  "101010101011111010101",
  "100010000010001000001",
  "111110101111101111101",
  "100000000000001000001",
  "101111111111101011111",
  "101000000000000000001",
  "101011111010111110101",
  "101010000000000000101",
  "101010101111111110101",
  "100010000000000000101",
  "101111111011111110101",
  "100000000000000000001",
  "111111111110111111111",
];

export const MAZE8_7_MAZE_GRID = WALL_ROWS.map((row) => [...row].map(Number));

export const MAZE8_7_MAZE_CONFIG = {
  id: "maze8-7-10x10",
  name: "10 by 10 matched maze 7 of 8",
  maze: MAZE8_7_MAZE_GRID,
  start: { x: 9, y: 1 },
  entrance: { x: 9, y: 0 },
  startFacing: 2,
  goal: { x: 11, y: 20 },
  hintSteps: 3,
  seed: 506,
};
