// Auto-generated by mazes8/scripts/build-set.mjs (seed 509, braiding 9).
// One of EIGHT mazes matched on difficulty: every maze in the set has exactly
// 33 branch points and a path length of 37 +/-2 moves.
// 16 loops, and 32 of the branch points have more than one branch that
// reaches the exit — so there is genuinely more than one correct path.
// Dead-end pockets are capped at 6 cells.
const WALL_ROWS = [
  "111111111011111111111",
  "100000000000000000001",
  "101011111110111110101",
  "101000000000100000101",
  "101010111110101111101",
  "101000100000101000101",
  "101010101010101010101",
  "101000100000101010001",
  "101111111110101010101",
  "100010000000100010101",
  "101010111111111010101",
  "101010000000000010101",
  "101011111010101010101",
  "101000100010000010101",
  "101010101010111110101",
  "100010100010000010101",
  "101010101111111010101",
  "100010001000000010101",
  "101011111011111110101",
  "100000001000000000001",
  "111111111110111111111",
];

export const MAZE8_8_MAZE_GRID = WALL_ROWS.map((row) => [...row].map(Number));

export const MAZE8_8_MAZE_CONFIG = {
  id: "maze8-8-10x10",
  name: "10 by 10 matched maze 8 of 8",
  maze: MAZE8_8_MAZE_GRID,
  start: { x: 9, y: 1 },
  entrance: { x: 9, y: 0 },
  startFacing: 2,
  goal: { x: 11, y: 20 },
  hintSteps: 3,
  seed: 509,
};
