// Auto-generated by mazes8/scripts/build-set.mjs (seed 147, braiding 2).
// One of EIGHT mazes matched on difficulty: every maze in the set has exactly
// 33 branch points and a path length of 37 +/-2 moves.
// 18 loops, and 32 of the branch points have more than one branch that
// reaches the exit — so there is genuinely more than one correct path.
// Dead-end pockets are capped at 6 cells.
const WALL_ROWS = [
  "111111111011111111111",
  "100000000000001000001",
  "101111111110101010101",
  "100010000000101000101",
  "101010101111101010101",
  "100010000000100000101",
  "101111101011111111101",
  "100010000010000000101",
  "101010101010111110101",
  "100010100010100000101",
  "101010111110101111101",
  "100010100000100000001",
  "101010101111101111101",
  "100010101000100000001",
  "101010101010101111101",
  "101010101000101000001",
  "101010101010101011111",
  "101000100000101000001",
  "101111101010101111101",
  "100000000000000000001",
  "111111111110111111111",
];

export const MAZE8_3_MAZE_GRID = WALL_ROWS.map((row) => [...row].map(Number));

export const MAZE8_3_MAZE_CONFIG = {
  id: "maze8-3-10x10",
  name: "10 by 10 matched maze 3 of 8",
  maze: MAZE8_3_MAZE_GRID,
  start: { x: 9, y: 1 },
  entrance: { x: 9, y: 0 },
  startFacing: 2,
  goal: { x: 11, y: 20 },
  hintSteps: 3,
  seed: 147,
};
