// Generate a maze MATCHED in size and complexity to a reference maze, so the two
// study conditions (AI vs no-AI) differ only in the AI, not in difficulty.
//
//   node scripts/build-matched-maze.mjs <reference_maze.js> <OUT_NAME>
//   e.g. node scripts/build-matched-maze.mjs public/no_ai_maze.js AI
//
// Matches: grid size, solution length, junction count, dead-end depth, and
// looplessness. Uses a recursive backtracker, which produces the same long winding
// character as mazegenerator.net rather than short bushy Prim's mazes.
import fs from "fs";
import path from "path";

const [refPath, outName] = process.argv.slice(2);
if (!refPath || !outName) { console.error("usage: build-matched-maze.mjs <reference_maze.js> <OUT_NAME>"); process.exit(1); }

function mulberry32(a){return()=>{a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}

function gridOf(src) {
  const rows = src.match(/"[01]+"/g).map((s) => s.replace(/"/g, ""));
  return rows.map((r) => r.split("").map(Number));
}
function metrics(g, start, goal) {
  const G = g.length;
  const isOpen = (x,y) => y>=0&&y<G&&x>=0&&x<G&&g[y][x]===0;
  const nbrs = (x,y) => [[0,-1],[1,0],[0,1],[-1,0]].map(([dx,dy])=>({x:x+dx,y:y+dy})).filter((c)=>isOpen(c.x,c.y));
  let cells=0, edges=0, junctions=0, deadEnds=0;
  for (let y=0;y<G;y++) for (let x=0;x<G;x++) {
    if (!isOpen(x,y)) continue; cells++;
    if (isOpen(x+1,y)) edges++; if (isOpen(x,y+1)) edges++;
    const n = nbrs(x,y).length;
    if (n >= 3) junctions++;
    if (n === 1) deadEnds++;
  }
  const seen = new Set([`${start.x},${start.y}`]); let f=[start], d=0, solution=Infinity;
  outer: while (f.length) { d++; const nx=[];
    for (const c of f) for (const n of nbrs(c.x,c.y)) {
      if (n.x===goal.x&&n.y===goal.y) { solution=d; break outer; }
      const k=`${n.x},${n.y}`; if (seen.has(k)) continue; seen.add(k); nx.push(n); }
    f=nx; }
  return { cells, loops: edges-(cells-1), junctions, deadEnds, solution, G };
}

// ---- reference ----
const refSrc = fs.readFileSync(refPath, "utf8");
const refGrid = gridOf(refSrc);
const refStart = { x: +refSrc.match(/start:\s*\{\s*x:\s*(\d+)/)[1], y: +refSrc.match(/start:\s*\{\s*x:\s*\d+,\s*y:\s*(\d+)/)[1] };
const refGoal  = { x: +refSrc.match(/goal:\s*\{\s*x:\s*(\d+)/)[1],  y: +refSrc.match(/goal:\s*\{\s*x:\s*\d+,\s*y:\s*(\d+)/)[1] };
const ref = metrics(refGrid, refStart, refGoal);
const G = ref.G, N = (G - 1) / 2;
console.log(`reference ${path.basename(refPath)}: ${N}x${N}, solution ${ref.solution}, junctions ${ref.junctions}, dead ends ${ref.deadEnds}, loops ${ref.loops}`);

// Same entrance/exit columns as the reference, so the two mazes start and end alike.
const entryCol = (refStart.x - 1) / 2;
const exitCol = (refGoal.x - 1) / 2;

// Recursive backtracker => long winding solutions, like the reference.
function carve(rng) {
  const g = Array.from({ length: G }, () => new Array(G).fill(1));
  for (let i=0;i<N;i++) for (let j=0;j<N;j++) g[2*j+1][2*i+1] = 0;
  const seen = new Set([`${entryCol},0`]);
  const stack = [[entryCol, 0]];
  while (stack.length) {
    const [i,j] = stack[stack.length-1];
    const opts = [[i+1,j],[i-1,j],[i,j+1],[i,j-1]].filter(([a,b]) => a>=0&&a<N&&b>=0&&b<N&&!seen.has(`${a},${b}`));
    if (!opts.length) { stack.pop(); continue; }
    const [a,b] = opts[Math.floor(rng()*opts.length)];
    g[j+b+1][i+a+1] = 0; seen.add(`${a},${b}`); stack.push([a,b]);
  }
  g[0][2*entryCol+1] = 0;      // entrance
  g[2*N][2*exitCol+1] = 0;     // exit
  return g;
}

const start = { x: 2*entryCol+1, y: 1 };
const goal = { x: 2*exitCol+1, y: 2*N };
let best = null;
for (let seed = 1; seed <= 60000; seed += 1) {
  const g = carve(mulberry32(seed));
  const m = metrics(g, start, goal);
  if (m.loops !== ref.loops) continue;
  const cost = Math.abs(m.solution - ref.solution) * 3
             + Math.abs(m.junctions - ref.junctions) * 6
             + Math.abs(m.deadEnds - ref.deadEnds) * 2;
  if (!best || cost < best.cost) best = { seed, g, m, cost };
  if (cost === 0) break;
}

const { seed, g, m } = best;
console.log(`matched   ${outName}: ${N}x${N}, solution ${m.solution}, junctions ${m.junctions}, dead ends ${m.deadEnds}, loops ${m.loops}   (seed ${seed})`);
console.log(`differences: solution ${m.solution-ref.solution >= 0 ? "+" : ""}${m.solution-ref.solution}, junctions ${m.junctions-ref.junctions >= 0 ? "+" : ""}${m.junctions-ref.junctions}, dead ends ${m.deadEnds-ref.deadEnds >= 0 ? "+" : ""}${m.deadEnds-ref.deadEnds}`);

const outFile = path.join("public", `${outName.toLowerCase()}_maze.js`);
fs.writeFileSync(outFile, `// Auto-generated by scripts/build-matched-maze.mjs (seed ${seed}).
// Complexity-MATCHED partner for ${path.basename(refPath)}, so the AI and no-AI
// conditions differ only in the AI:
//   this maze : solution ${m.solution} steps, ${m.junctions} junctions, ${m.deadEnds} dead ends, ${m.loops} loops
//   reference : solution ${ref.solution} steps, ${ref.junctions} junctions, ${ref.deadEnds} dead ends, ${ref.loops} loops
// Same ${N}x${N} size and the same entrance/exit columns.
const WALL_ROWS = [
${g.map((r)=>`  "${r.join("")}",`).join("\n")}
];

export const ${outName}_MAZE_GRID = WALL_ROWS.map((row) => [...row].map(Number));

export const ${outName}_MAZE_CONFIG = {
  id: "${outName.toLowerCase()}-${N}x${N}",
  name: "${N} by ${N} maze (${outName} condition)",
  maze: ${outName}_MAZE_GRID,
  start: { x: ${start.x}, y: ${start.y} },
  entrance: { x: ${start.x}, y: 0 },
  startFacing: 2,
  goal: { x: ${goal.x}, y: ${goal.y} },
  hintSteps: 3,
  seed: ${seed},
};
`);
console.log(`wrote ${outFile}`);
